name: Build and deploy to GitHub Pages
on:
  push:
    branches: [main, master]
    paths:
      - '.github/workflows/website.yml'
      - 'docs/**'
      - '**.md'
      - 'cecil.yml'
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: pre-installed
          extensions: mbstring, fileinfo, gd, imagick, intl, gettext, :redis
      - name: Setup Pages
        id: pages
        uses: actions/configure-pages@v5
      - name: Build with Cecil
        uses: Cecilapp/Cecil-Action@v3
        with:
          config: 'cecil.yml'
          args: '-v --baseurl="${{ steps.pages.outputs.base_url }}/"'
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v5
  deploy:
    needs: build
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v5
